name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Flutter SDK
        shell: bash
        run: |
          git clone https://github.com/flutter/flutter.git --branch stable --depth 1 /tmp/flutter
          echo "/tmp/flutter/bin" >> "$GITHUB_PATH"
          echo "/tmp/flutter/bin/cache/dart-sdk/bin" >> "$GITHUB_PATH"
          export PATH="/tmp/flutter/bin:$PATH"
          flutter --version

      - name: Enable Android licenses
        shell: bash
        run: yes | flutter doctor --android-licenses

      - name: Install dependencies
        run: flutter pub get

      - name: Run Flutter analyze
        run: flutter analyze

      - name: Run Flutter tests
        run: flutter test --coverage

      - name: Build APK
        run: flutter build apk --release

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: live-tv-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
